### ISSUE TITLE
Project has no listing of minimum compatible OSes, drivers and GPUs

### ISSUE THREAD

**Issue by Hyenadae** [minecrafthome/minecrafthome#24]
At the moment we can break this down into:

Windows (64bit): Latest Windows 7, but Windows 10 preferred.
Linux (64bit) Ubuntu 16.04 / Fedora 24 or newer. Major requirement is  GLIBC at version 2.23 or newer

Any Nvidia GPU at or after Kepler (600 -> RTX series) with OpenCL 1.2 
Windows: Any Nvidia driver within the past two years, at least
Linux: Proprietary Nvidia 400+ *with opencl headers installed by  nvidia-opencl-dev package as well*

Any AMD GPU with GCN 1.2 architecture & OpenCL 2.0  (Some RX 200/300 GPUs, all RX 400/500, Vega and RX 5000 series)
Windows: Adrenalin 18.12 or newer. Older Polaris (RX 460/480) and Vega most stable with drivers before Adrenaline 2020
Linux: ROCM - https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html  third-party repository for OCL 2.0

Any Intel GPU that is 6th gen or newer for OpenCL 2.0 drivers.
Windows: Latest Intel standalone drivers if possible to ensure OpenCL environment is installed
Linux: beignet-opencl-icd and beignet packages on a user's distro. Provides OpenCL 2.0 to "Skylake" or newer iGPUs without issue

**Comment by ChipWolf** [comment]
We'd just need to adjust the plan classes as a first step.
